dist: xenial
os: linux
version: ~> 1.0
language: cpp

branches:
  only:
  - staging
  - trying
  - master
  # release branch
  - /^release\/[\d\.]+$/
  # release tag
  - /^v[\d\.]+$/

addons:
  snaps:
  -  lxd

stages:
- name: test
- name: upload to ppa:mir-team
  if: type = push
      AND repo = MirServer/wlcs
      AND ( branch = master
            OR branch =~ ^release/[\d\.]+$
            OR tag =~ ^v[\d\.]+$ )

install:
  - sudo adduser $USER lxd
  - sudo apt remove --assume-yes lxd
  - wget https://people.canonical.com/~chrishr/spread.snap
  - sudo snap run lxd init --auto
  - sudo snap install --dangerous spread.snap
  - sudo snap connect spread:lxd lxd:lxd

env:
  global:
  - DEBFULLNAME="Mir CI Bot"
  - DEBEMAIL="mir-ci-bot@canonical.com"
  jobs:
  - SYSTEM=ubuntu-16.04 VARIANT=gcc
  - SYSTEM=ubuntu-18.04 VARIANT=gcc
  - SYSTEM=ubuntu-19.10 VARIANT=gcc
  - SYSTEM=ubuntu-devel VARIANT=gcc
  - SYSTEM=ubuntu-devel VARIANT=clang
  - SYSTEM=fedora-29 VARIANT=gcc
  - SYSTEM=fedora-30 VARIANT=gcc
  - SYSTEM=alpine-3.10 VARIANT=gcc

script:
  - sg lxd -c 'LXD_DIR=/var/snap/lxd/common/lxd snap run spread lxd:$SYSTEM:...:$VARIANT'

jobs:
  include:
  - &ppa-upload
    stage: upload to ppa:mir-team
    env: RELEASE=16.04
    git:
      depth: false
    before_install: &decrypt-bot-data
    - openssl aes-256-cbc -K $encrypted_de81f8095dc8_key -iv $encrypted_de81f8095dc8_iv -in tools/bot-data.tar.xz.enc -out /tmp/bot-data.tar.xz -d
    - tar --verbose --extract --xz --file /tmp/bot-data.tar.xz --directory ${HOME}
    # We don't need to do the install steps
    install: skip
    script:
    - tools/ppa-upload.sh
    addons:
      apt:
        packages:
        - debhelper
        - devscripts
        - dput
        - fakeroot
        - python-bzrlib
        - python-launchpadlib
        - python-paramiko
        - libdistro-info-perl
  - <<: *ppa-upload
    env: RELEASE=18.04
  - <<: *ppa-upload
    env: RELEASE=19.10
  - <<: *ppa-upload
    env: RELEASE=devel

