# Needed so we can install snaps
sudo: required
dist: trusty

language: cpp

branches:
  only:
  - staging
  - trying
  - master

install:
  - sudo apt-get --yes --no-install-recommends install snapd
  - sudo snap install lxd
  - sudo addgroup --system lxd
  - sudo adduser $USER lxd
  - sudo lxd waitready
  - sudo lxd init --auto
  - wget https://cooperteam.net/spread_2017.09.21_amd64.snap
  - sudo snap install --dangerous spread_2017.09.21_amd64.snap
  - sudo snap connect spread:lxd lxd:lxd

env:
  matrix:
  - SYSTEM=ubuntu-16.04 VARIANT=gcc
  - SYSTEM=ubuntu-17.10 VARIANT=gcc
  - SYSTEM=ubuntu-17.10 VARIANT=clang
  - SYSTEM=fedora-26 VARIANT=gcc

script:
  - sg lxd -c 'LXD_DIR=/var/snap/lxd/common/lxd /snap/bin/spread lxd:$SYSTEM:...:$VARIANT'
